/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.vetsys.view.manager;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import project.vetsys.view.security.LogIn;
import javax.swing.JOptionPane;
import project.vetsys.model.Role;
import project.vetsys.model.Status;
import project.vetsys.model.User;
import project.vetsys.dao.ClienteDAO;
import project.vetsys.database.DBConnection;
import project.vetsys.model.ClienteModel;
import project.vetsys.view.ComboBox;
import project.vetsys.view.manager.MenuManager;

/**
 *
 * @author San
 */
public class CreateClient extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateClient.class.getName());
    private User logUser;
    private final ClienteDAO clienteDAO = new ClienteDAO();
    
    /**
     * Creates new form SearchUser
     * @param logUser
     */
    
    public CreateClient() {
        initComponents();
        initListeners();
    }
    
    public CreateClient(User logUser) {
        this.logUser = logUser;
        initComponents();
        initListeners();
        cargarMembresias();
       
    }
    
    private void initListeners() {
        //cboxRoleCreate.addActionListener(e -> loadRolesStatus());
        //cboxStatusCreate.addActionListener(e-> loadRolesStatus());
    }
    
    private void limpiarCampos() {
        txtNombreCliente.setText("");
        txtApellidos.setText("");
        txtDocumento.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        jFormattedTextFechaInicioMembresia.setText("");
        jFormattedTextFechaFinMembresia.setText("");
        jComboBoxMembresia.setSelectedIndex(0);
    }
    
    private void cargarMembresias() {
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT id_membresia, nombre FROM membresia WHERE id_clinica = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, logUser.getId_clinic()); // filtrar según clínica del usuario
            ResultSet rs = ps.executeQuery();

            DefaultComboBoxModel<String> modelocmbox = new DefaultComboBoxModel<>();
            jComboBoxMembresia.removeAllItems();

            while (rs.next()) {
                int id = rs.getInt("id_membresia");
                String nombre = rs.getString("nombre");
                // Guardar el ID de la membresía asociado al nombre
                jComboBoxMembresia.addItem(id + " - " + nombre);
            }

            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar membresías: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        CreateUserPanel = new javax.swing.JPanel();
        Up = new javax.swing.JPanel();
        CreateUser_lblTittle = new javax.swing.JLabel();
        Down = new javax.swing.JPanel();
        CreateUser_lblSubTittle = new javax.swing.JLabel();
        CreateUser_lblName = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        CreateUser_LastName = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        CreateUser_lblPhone = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        CreateUser_lbl_ID = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        CreateUser_lblEmail = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        CreateUser_lblMembresia = new javax.swing.JLabel();
        CreateUser_lblFechaIni = new javax.swing.JLabel();
        CreateUser_BttnBack = new javax.swing.JPanel();
        CreateUser_lblBttnBack = new javax.swing.JLabel();
        CreateUser_lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        CreateUser_lblFechaFin = new javax.swing.JLabel();
        jFormattedTextFechaInicioMembresia = new javax.swing.JFormattedTextField();
        jFormattedTextFechaFinMembresia = new javax.swing.JFormattedTextField();
        jComboBoxMembresia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreateUser_BttnRegister = new javax.swing.JPanel();
        CreateUser_lblBttnRegister = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateUserPanel.setMaximumSize(new java.awt.Dimension(1000, 800));
        CreateUserPanel.setMinimumSize(new java.awt.Dimension(1000, 800));
        CreateUserPanel.setPreferredSize(new java.awt.Dimension(1000, 800));
        CreateUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Up.setBackground(new java.awt.Color(0, 153, 153));
        Up.setMaximumSize(new java.awt.Dimension(1000, 100));
        Up.setMinimumSize(new java.awt.Dimension(1000, 100));
        Up.setPreferredSize(new java.awt.Dimension(1000, 100));

        CreateUser_lblTittle.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        CreateUser_lblTittle.setForeground(new java.awt.Color(255, 255, 255));
        CreateUser_lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateUser_lblTittle.setText("VetSys");

        javax.swing.GroupLayout UpLayout = new javax.swing.GroupLayout(Up);
        Up.setLayout(UpLayout);
        UpLayout.setHorizontalGroup(
            UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateUser_lblTittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        UpLayout.setVerticalGroup(
            UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpLayout.createSequentialGroup()
                .addComponent(CreateUser_lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CreateUserPanel.add(Up, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        Down.setBackground(new java.awt.Color(255, 255, 255));
        Down.setMaximumSize(new java.awt.Dimension(1000, 700));
        Down.setMinimumSize(new java.awt.Dimension(1000, 700));
        Down.setPreferredSize(new java.awt.Dimension(1000, 700));

        CreateUser_lblSubTittle.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        CreateUser_lblSubTittle.setForeground(new java.awt.Color(0, 153, 153));
        CreateUser_lblSubTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateUser_lblSubTittle.setText("Registro de Cliente");

        CreateUser_lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblName.setText("Nombre completo");

        txtNombreCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombreCliente.setForeground(java.awt.Color.gray);
        txtNombreCliente.setMinimumSize(new java.awt.Dimension(68, 26));
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(68, 26));
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreClienteMousePressed(evt);
            }
        });
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        CreateUser_LastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_LastName.setText("Apellidos");

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellidos.setForeground(java.awt.Color.gray);
        txtApellidos.setMinimumSize(new java.awt.Dimension(68, 26));
        txtApellidos.setPreferredSize(new java.awt.Dimension(68, 26));
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        CreateUser_lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblPhone.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.gray);
        txtTelefono.setMinimumSize(new java.awt.Dimension(68, 26));
        txtTelefono.setPreferredSize(new java.awt.Dimension(68, 26));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        CreateUser_lbl_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lbl_ID.setText("Documento");

        txtDocumento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDocumento.setForeground(java.awt.Color.gray);
        txtDocumento.setMinimumSize(new java.awt.Dimension(68, 26));
        txtDocumento.setPreferredSize(new java.awt.Dimension(68, 26));
        txtDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDocumentoMousePressed(evt);
            }
        });
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        CreateUser_lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblEmail.setText("Correo electronico");

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.gray);
        txtCorreo.setMinimumSize(new java.awt.Dimension(68, 26));
        txtCorreo.setPreferredSize(new java.awt.Dimension(68, 26));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        CreateUser_lblMembresia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblMembresia.setText("Membresía");

        CreateUser_lblFechaIni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblFechaIni.setText("Fecha de inicio");

        CreateUser_BttnBack.setBackground(new java.awt.Color(0, 153, 153));
        CreateUser_BttnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CreateUser_lblBttnBack.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        CreateUser_lblBttnBack.setForeground(new java.awt.Color(255, 255, 255));
        CreateUser_lblBttnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateUser_lblBttnBack.setText("Regresar");
        CreateUser_lblBttnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateUser_lblBttnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CreateUser_BttnBackLayout = new javax.swing.GroupLayout(CreateUser_BttnBack);
        CreateUser_BttnBack.setLayout(CreateUser_BttnBackLayout);
        CreateUser_BttnBackLayout.setHorizontalGroup(
            CreateUser_BttnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateUser_lblBttnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        CreateUser_BttnBackLayout.setVerticalGroup(
            CreateUser_BttnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUser_BttnBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateUser_lblBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CreateUser_lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblDireccion.setText("Dirección");

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDireccion.setForeground(java.awt.Color.gray);
        txtDireccion.setMinimumSize(new java.awt.Dimension(68, 26));
        txtDireccion.setPreferredSize(new java.awt.Dimension(68, 26));
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        CreateUser_lblFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateUser_lblFechaFin.setText("Fecha de vigencia");

        jFormattedTextFechaInicioMembresia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/MM/d"))));

        jFormattedTextFechaFinMembresia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/MM/d"))));
        jFormattedTextFechaFinMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFechaFinMembresiaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("yyyy/mm/dd");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("yyyy/mm/dd");

        CreateUser_BttnRegister.setBackground(new java.awt.Color(0, 153, 153));
        CreateUser_BttnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CreateUser_lblBttnRegister.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        CreateUser_lblBttnRegister.setForeground(new java.awt.Color(255, 255, 255));
        CreateUser_lblBttnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateUser_lblBttnRegister.setText("Registrar");
        CreateUser_lblBttnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateUser_lblBttnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateUser_lblBttnRegisterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CreateUser_BttnRegisterLayout = new javax.swing.GroupLayout(CreateUser_BttnRegister);
        CreateUser_BttnRegister.setLayout(CreateUser_BttnRegisterLayout);
        CreateUser_BttnRegisterLayout.setHorizontalGroup(
            CreateUser_BttnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateUser_lblBttnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        CreateUser_BttnRegisterLayout.setVerticalGroup(
            CreateUser_BttnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUser_BttnRegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateUser_lblBttnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout DownLayout = new javax.swing.GroupLayout(Down);
        Down.setLayout(DownLayout);
        DownLayout.setHorizontalGroup(
            DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateUser_lblSubTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DownLayout.createSequentialGroup()
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DownLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CreateUser_lblName)
                                .addComponent(CreateUser_LastName)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DownLayout.createSequentialGroup()
                                    .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CreateUser_lbl_ID)
                                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                    .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CreateUser_lblPhone))))
                            .addComponent(CreateUser_lblEmail)
                            .addComponent(CreateUser_lblDireccion))
                        .addGap(27, 27, 27)
                        .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateUser_lblMembresia)
                            .addGroup(DownLayout.createSequentialGroup()
                                .addComponent(CreateUser_lblFechaIni)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(DownLayout.createSequentialGroup()
                                .addComponent(CreateUser_lblFechaFin)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(jFormattedTextFechaFinMembresia)
                            .addComponent(jFormattedTextFechaInicioMembresia)
                            .addComponent(jComboBoxMembresia, 0, 377, Short.MAX_VALUE)))
                    .addGroup(DownLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(CreateUser_BttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DownLayout.createSequentialGroup()
                    .addContainerGap(601, Short.MAX_VALUE)
                    .addComponent(CreateUser_BttnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(224, 224, 224)))
        );
        DownLayout.setVerticalGroup(
            DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DownLayout.createSequentialGroup()
                .addComponent(CreateUser_lblSubTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateUser_lblName)
                    .addComponent(CreateUser_lblMembresia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateUser_lblFechaIni)
                    .addComponent(CreateUser_LastName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFechaInicioMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateUser_lbl_ID)
                    .addComponent(CreateUser_lblPhone)
                    .addComponent(CreateUser_lblFechaFin)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFechaFinMembresia))
                .addGap(18, 18, 18)
                .addComponent(CreateUser_lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateUser_lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(CreateUser_BttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DownLayout.createSequentialGroup()
                    .addContainerGap(570, Short.MAX_VALUE)
                    .addComponent(CreateUser_BttnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)))
        );

        CreateUser_lblName.getAccessibleContext().setAccessibleDescription("lblName");

        CreateUserPanel.add(Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreateUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreateUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed

    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDocumentoMousePressed
        
    }//GEN-LAST:event_txtDocumentoMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed

    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        
    }//GEN-LAST:event_txtApellidosMousePressed

    private void txtNombreClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMousePressed
        
    }//GEN-LAST:event_txtNombreClienteMousePressed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionMousePressed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void CreateUser_lblBttnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnBackMouseExited
        CreateUser_BttnBack.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_CreateUser_lblBttnBackMouseExited

    private void CreateUser_lblBttnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnBackMouseEntered
        CreateUser_BttnBack.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CreateUser_lblBttnBackMouseEntered

    private void CreateUser_lblBttnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnBackMouseClicked
        
        PatientsMenu MenuPatients = new PatientsMenu(logUser);
        MenuPatients.setVisible(true);
        MenuPatients.pack();
        MenuPatients.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_CreateUser_lblBttnBackMouseClicked

    private void jFormattedTextFechaFinMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFechaFinMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFechaFinMembresiaActionPerformed

    private void CreateUser_lblBttnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnRegisterMouseClicked
        try {
            // Validar campos vacíos
            if (txtNombreCliente.getText().trim().isEmpty() ||
                txtApellidos.getText().trim().isEmpty() ||
                txtDocumento.getText().trim().isEmpty() ||
                txtTelefono.getText().trim().isEmpty() ||
                txtCorreo.getText().trim().isEmpty() ||
                txtDireccion.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, 
                    "Por favor complete todos los campos.", 
                    "Campos vacíos", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //Obtener id de la membresía seleccionada
            String itemSeleccionado = (String) jComboBoxMembresia.getSelectedItem();
            int idMembresia = 0;
            if (itemSeleccionado != null && itemSeleccionado.contains(" - ")) {
                idMembresia = Integer.parseInt(itemSeleccionado.split(" - ")[0]);
            }

            // Crear objeto cliente
            ClienteModel cliente = new ClienteModel();
            cliente.setIdClinica(logUser.getId_clinic()); // desde el usuario logueado
            cliente.setNombres(txtNombreCliente.getText());
            cliente.setApellidos(txtApellidos.getText());
            cliente.setDocumento(txtDocumento.getText());
            cliente.setTelefono(txtTelefono.getText());
            cliente.setCorreo(txtCorreo.getText());
            cliente.setDireccion(txtDireccion.getText());
            cliente.setIdMembresia(jComboBoxMembresia.getSelectedIndex() + 1);
            cliente.setFechaInicio(jFormattedTextFechaInicioMembresia.getText());
            cliente.setFechaVigencia(jFormattedTextFechaFinMembresia.getText());
            cliente.setEstadoMembresia(1);

            // Insertar cliente DAO a la BD 
            ClienteDAO clienteDAO = new ClienteDAO();
            boolean registrado = clienteDAO.insertarCliente(cliente);

            if (registrado) {
                JOptionPane.showMessageDialog(this, 
                    "Cliente registrado correctamente", 
                    "Exito", 
                    JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo registrar el cliente", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al registrar el cliente: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CreateUser_lblBttnRegisterMouseClicked

    private void CreateUser_lblBttnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnRegisterMouseEntered
        CreateUser_BttnBack.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CreateUser_lblBttnRegisterMouseEntered

    private void CreateUser_lblBttnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateUser_lblBttnRegisterMouseExited
        CreateUser_BttnBack.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_CreateUser_lblBttnRegisterMouseExited

    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new CreateClient().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateUserPanel;
    private javax.swing.JPanel CreateUser_BttnBack;
    private javax.swing.JPanel CreateUser_BttnRegister;
    private javax.swing.JLabel CreateUser_LastName;
    private javax.swing.JLabel CreateUser_lblBttnBack;
    private javax.swing.JLabel CreateUser_lblBttnRegister;
    private javax.swing.JLabel CreateUser_lblDireccion;
    private javax.swing.JLabel CreateUser_lblEmail;
    private javax.swing.JLabel CreateUser_lblFechaFin;
    private javax.swing.JLabel CreateUser_lblFechaIni;
    private javax.swing.JLabel CreateUser_lblMembresia;
    private javax.swing.JLabel CreateUser_lblName;
    private javax.swing.JLabel CreateUser_lblPhone;
    private javax.swing.JLabel CreateUser_lblSubTittle;
    private javax.swing.JLabel CreateUser_lblTittle;
    private javax.swing.JLabel CreateUser_lbl_ID;
    private javax.swing.JPanel Down;
    private javax.swing.JPanel Up;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxMembresia;
    private javax.swing.JFormattedTextField jFormattedTextFechaFinMembresia;
    private javax.swing.JFormattedTextField jFormattedTextFechaInicioMembresia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
