/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.vetsys.view.manager;

import java.awt.Color;
import java.sql.Date;
import project.vetsys.model.User;
import javax.swing.JOptionPane;
import project.vetsys.dao.PetDAO;
import project.vetsys.model.Pet;

/**
 *
 * @author User
 */
public class CreatePet extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreatePet.class.getName());
    private User logUser;

    /**
     * Creates new form CreatePet
     */
    public CreatePet() {
        initComponents();
    }
    
    public CreatePet(User logUser){
        initComponents();
        this.logUser = logUser;
    }
    
    
    private void initListeners() {
       CreatePet_BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_BtnCreateActionPerformed(evt);  // Llamamos al método que manejas
            }
    });

    CreatePet_BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreatePet = new javax.swing.JPanel();
        CreateUser_lblSubTittle = new javax.swing.JLabel();
        CreatePet_lblNamepet = new javax.swing.JLabel();
        CreatePet_NameField = new javax.swing.JTextField();
        CreatePet_lblSpecies = new javax.swing.JLabel();
        CreatePet_SpeciesFiel = new javax.swing.JTextField();
        CreatePet_lblBred = new javax.swing.JLabel();
        CreatePet_BredField = new javax.swing.JTextField();
        CreatePet_lblColor = new javax.swing.JLabel();
        CreatePet_ColorField = new javax.swing.JTextField();
        CreatePet_lblSex = new javax.swing.JLabel();
        CreatePet_SexField = new javax.swing.JTextField();
        CreatePet_lblDate = new javax.swing.JLabel();
        CreatePet_DateOfBirthField = new javax.swing.JTextField();
        CreatePet_DocumentOwner = new javax.swing.JTextField();
        CreatePet_lblDocumentOwner = new javax.swing.JLabel();
        CreatePet_BtnCreate = new javax.swing.JButton();
        CreatePet_BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreatePet.setBackground(new java.awt.Color(255, 255, 255));
        CreatePet.setMaximumSize(new java.awt.Dimension(1000, 700));
        CreatePet.setMinimumSize(new java.awt.Dimension(1000, 700));

        CreateUser_lblSubTittle.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        CreateUser_lblSubTittle.setForeground(new java.awt.Color(0, 153, 153));
        CreateUser_lblSubTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateUser_lblSubTittle.setText("Crear Mascota");

        CreatePet_lblNamepet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblNamepet.setText("Nombre");

        CreatePet_NameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_NameField.setForeground(java.awt.Color.gray);
        CreatePet_NameField.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_NameField.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_NameFieldMousePressed(evt);
            }
        });
        CreatePet_NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_NameFieldActionPerformed(evt);
            }
        });

        CreatePet_lblSpecies.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblSpecies.setText("Especie");

        CreatePet_SpeciesFiel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_SpeciesFiel.setForeground(java.awt.Color.gray);
        CreatePet_SpeciesFiel.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_SpeciesFiel.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_SpeciesFiel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_SpeciesFielMousePressed(evt);
            }
        });
        CreatePet_SpeciesFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_SpeciesFielActionPerformed(evt);
            }
        });

        CreatePet_lblBred.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblBred.setText("Raza");

        CreatePet_BredField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_BredField.setForeground(java.awt.Color.gray);
        CreatePet_BredField.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_BredField.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_BredField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_BredFieldMousePressed(evt);
            }
        });
        CreatePet_BredField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_BredFieldActionPerformed(evt);
            }
        });

        CreatePet_lblColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblColor.setText("Color");

        CreatePet_ColorField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_ColorField.setForeground(java.awt.Color.gray);
        CreatePet_ColorField.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_ColorField.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_ColorField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_ColorFieldMousePressed(evt);
            }
        });
        CreatePet_ColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_ColorFieldActionPerformed(evt);
            }
        });

        CreatePet_lblSex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblSex.setText("Sexo");

        CreatePet_SexField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_SexField.setForeground(java.awt.Color.gray);
        CreatePet_SexField.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_SexField.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_SexField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_SexFieldMousePressed(evt);
            }
        });
        CreatePet_SexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_SexFieldActionPerformed(evt);
            }
        });

        CreatePet_lblDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblDate.setText("Fecha de Nacimiento");

        CreatePet_DateOfBirthField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_DateOfBirthField.setForeground(java.awt.Color.gray);
        CreatePet_DateOfBirthField.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_DateOfBirthField.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_DateOfBirthField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_DateOfBirthFieldMousePressed(evt);
            }
        });
        CreatePet_DateOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_DateOfBirthFieldActionPerformed(evt);
            }
        });

        CreatePet_DocumentOwner.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_DocumentOwner.setForeground(java.awt.Color.gray);
        CreatePet_DocumentOwner.setMinimumSize(new java.awt.Dimension(68, 26));
        CreatePet_DocumentOwner.setPreferredSize(new java.awt.Dimension(68, 26));
        CreatePet_DocumentOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreatePet_DocumentOwnerMousePressed(evt);
            }
        });
        CreatePet_DocumentOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_DocumentOwnerActionPerformed(evt);
            }
        });

        CreatePet_lblDocumentOwner.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreatePet_lblDocumentOwner.setText("Cedula Propietario");

        CreatePet_BtnCreate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_BtnCreate.setForeground(new java.awt.Color(0, 102, 102));
        CreatePet_BtnCreate.setText("Crear");
        CreatePet_BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_BtnCreateActionPerformed(evt);
            }
        });

        CreatePet_BtnExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CreatePet_BtnExit.setForeground(new java.awt.Color(0, 102, 102));
        CreatePet_BtnExit.setText("Salir");
        CreatePet_BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePet_BtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreatePetLayout = new javax.swing.GroupLayout(CreatePet);
        CreatePet.setLayout(CreatePetLayout);
        CreatePetLayout.setHorizontalGroup(
            CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateUser_lblSubTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CreatePetLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreatePet_lblNamepet)
                    .addComponent(CreatePet_lblSex)
                    .addGroup(CreatePetLayout.createSequentialGroup()
                        .addGroup(CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreatePet_lblBred)
                            .addComponent(CreatePet_lblColor)
                            .addComponent(CreatePet_lblSpecies)
                            .addComponent(CreatePet_ColorField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(CreatePet_BredField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreatePet_SpeciesFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreatePet_NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreatePet_SexField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(177, 177, 177)
                        .addGroup(CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreatePet_lblDate)
                            .addComponent(CreatePet_DateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreatePet_lblDocumentOwner)
                            .addComponent(CreatePet_DocumentOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePetLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(CreatePet_BtnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreatePet_BtnExit)
                .addGap(248, 248, 248))
        );
        CreatePetLayout.setVerticalGroup(
            CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateUser_lblSubTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePetLayout.createSequentialGroup()
                        .addComponent(CreatePet_lblNamepet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_lblSpecies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_SpeciesFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_lblBred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_BredField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_lblColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_ColorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_lblSex))
                    .addGroup(CreatePetLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(CreatePet_lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_DateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CreatePet_lblDocumentOwner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePet_DocumentOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreatePet_SexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(CreatePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreatePet_BtnCreate)
                    .addComponent(CreatePet_BtnExit))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreatePet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatePet, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreatePet_BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_BtnExitActionPerformed
      
        MenuManager MenuManagerFrame = new MenuManager(logUser);
        MenuManagerFrame.setVisible(true);
        MenuManagerFrame.pack();
        MenuManagerFrame.setLocationRelativeTo(null);
        this.dispose();
             
        
      
    }//GEN-LAST:event_CreatePet_BtnExitActionPerformed

    private void CreatePet_BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_BtnCreateActionPerformed
        // TODO add your handling code here:
        
        String namePet = CreatePet_NameField.getText();
        String speciesPet = CreatePet_SpeciesFiel.getText();
        String bredPet = CreatePet_BredField.getText();
        String colorPet = CreatePet_ColorField.getText();
        String sexPet = CreatePet_SexField.getText();
        String datePet = CreatePet_DateOfBirthField.getText();
        String documentOwner = CreatePet_DocumentOwner.getText();
        
        if (namePet.isEmpty() || documentOwner.isEmpty() || speciesPet.isEmpty() || bredPet.isEmpty() 
                ||colorPet.isEmpty() || sexPet.isEmpty() || datePet.isEmpty()  ) 
        {
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos obligatorios");
            return;
        }
        
        Pet pet = new Pet();
        PetDAO petDao = new PetDAO();
        pet.setName_Pet(namePet);
        pet.setSpecies(speciesPet);
        pet.setBred(bredPet);
        pet.setColor(colorPet);
        pet.setSex(sexPet);
        pet.setDate_of_birth(Date.valueOf(datePet));
        int document = petDao.searchIdOwner(documentOwner); ///pasar el documento para buscar el idCliente
        pet.setId_Client(document);
        pet.setId_Clinic(logUser.getId_clinic());
        
        boolean success = petDao.Create(pet, documentOwner);
        
        if(success){
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario creado correctamente");
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al crear el usuario. Revisa los datos o la conexión.");
        }
       
    }//GEN-LAST:event_CreatePet_BtnCreateActionPerformed

    private void CreatePet_DocumentOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_DocumentOwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_DocumentOwnerActionPerformed

    private void CreatePet_DocumentOwnerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_DocumentOwnerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_DocumentOwnerMousePressed

    private void CreatePet_DateOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_DateOfBirthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_DateOfBirthFieldActionPerformed

    private void CreatePet_DateOfBirthFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_DateOfBirthFieldMousePressed
       /* if (CreatePet_DateOfBirthField.getText().equals("YYYY-MM-DD")){
            CreatePet_DateOfBirthField.setText("");
            CreatePet_DateOfBirthField.setForeground(Color.black);
        }
        if (CreatePet_NameField.getText().isEmpty()){
            CreatePet_NameField.setText("Ingrese Nombre");
            CreatePet_NameField.setForeground(Color.gray);
        }
        if (CreatePet_SpeciesFiel.getText().isEmpty()){
            CreatePet_SpeciesFiel.setText("Ingrese Especie");
            CreatePet_SpeciesFiel.setForeground(Color.gray);
        }
        if (CreatePet_BredField.getText().isEmpty()){
            CreatePet_BredField.setText("Ingrese Raza");
            CreatePet_BredField.setForeground(Color.gray);
        }
        if (CreatePet_ColorField.getText().isEmpty()){
            CreatePet_ColorField.setText("Ingrese Color");
            CreatePet_ColorField.setForeground(Color.gray);
        }
        if (CreatePet_SexField.getText().isEmpty()){
            CreatePet_SexField.setText("Ingrese Sexo");
            CreatePet_SexField.setForeground(Color.gray);
        }*/
       
    }//GEN-LAST:event_CreatePet_DateOfBirthFieldMousePressed

    private void CreatePet_SexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_SexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_SexFieldActionPerformed

    private void CreatePet_SexFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_SexFieldMousePressed
        /*if (CreatePet_SexField.getText().equals("Ingrese sexo")){
            CreatePet_SexField.setText("");
            CreatePet_SexField.setForeground(Color.black);
        }
        if (CreatePet_NameField.getText().isEmpty()){
            CreatePet_NameField.setText("Ingrese Nombre");
            CreatePet_NameField.setForeground(Color.gray);
        }
        if (CreatePet_SpeciesFiel.getText().isEmpty()){
            CreatePet_SpeciesFiel.setText("Ingrese Especie");
            CreatePet_SpeciesFiel.setForeground(Color.gray);
        }
        if (CreatePet_BredField.getText().isEmpty()){
            CreatePet_BredField.setText("Ingrese Raza");
            CreatePet_BredField.setForeground(Color.gray);
        }
        if (CreatePet_ColorField.getText().isEmpty()){
            CreatePet_ColorField.setText("Ingrese Color");
            CreatePet_ColorField.setForeground(Color.gray);
        }
        if (CreatePet_DateOfBirthField.getText().isEmpty()){
            CreatePet_DateOfBirthField.setText("YYYY-MM-DD");
            CreatePet_DateOfBirthField.setForeground(Color.gray);
        }*/
       
    }//GEN-LAST:event_CreatePet_SexFieldMousePressed

    private void CreatePet_ColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_ColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_ColorFieldActionPerformed

    private void CreatePet_ColorFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_ColorFieldMousePressed
        /*if (CreatePet_ColorField.getText().equals("Ingrese Color")){
            CreatePet_ColorField.setText("");
            CreatePet_ColorField.setForeground(Color.black);
        }
        if (CreatePet_NameField.getText().isEmpty()){
            CreatePet_NameField.setText("Ingrese Nombre");
            CreatePet_NameField.setForeground(Color.gray);
        }
        if (CreatePet_SpeciesFiel.getText().isEmpty()){
            CreatePet_SpeciesFiel.setText("Ingrese Especie");
            CreatePet_SpeciesFiel.setForeground(Color.gray);
        }
        if (CreatePet_BredField.getText().isEmpty()){
            CreatePet_BredField.setText("Ingrese Raza");
            CreatePet_BredField.setForeground(Color.gray);
        }
        if (CreatePet_SexField.getText().isEmpty()){
            CreatePet_SexField.setText("Ingrese Sexo");
            CreatePet_SexField.setForeground(Color.gray);
        }
        if (CreatePet_DateOfBirthField.getText().isEmpty()){
            CreatePet_DateOfBirthField.setText("YYYY-MM-DD");
            CreatePet_DateOfBirthField.setForeground(Color.gray);
        }*/
      
    }//GEN-LAST:event_CreatePet_ColorFieldMousePressed

    private void CreatePet_BredFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_BredFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_BredFieldActionPerformed

    private void CreatePet_BredFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_BredFieldMousePressed
        /*if (CreatePet_BredField.getText().equals("Ingrese Raza")){
            CreatePet_BredField.setText("");
            CreatePet_BredField.setForeground(Color.black);
        }
        if (CreatePet_NameField.getText().isEmpty()){
            CreatePet_NameField.setText("Ingrese Nombre");
            CreatePet_NameField.setForeground(Color.gray);
        }
        if (CreatePet_SpeciesFiel.getText().isEmpty()){
            CreatePet_SpeciesFiel.setText("Ingrese Especie");
            CreatePet_SpeciesFiel.setForeground(Color.gray);
        }
        if (CreatePet_ColorField.getText().isEmpty()){
            CreatePet_ColorField.setText("Ingrese Color");
            CreatePet_ColorField.setForeground(Color.gray);
        }
        if (CreatePet_SexField.getText().isEmpty()){
            CreatePet_SexField.setText("Ingrese Sexo");
            CreatePet_SexField.setForeground(Color.gray);
        }
        if (CreatePet_DateOfBirthField.getText().isEmpty()){
            CreatePet_DateOfBirthField.setText("YYYY-MM-DD");
            CreatePet_DateOfBirthField.setForeground(Color.gray);
        }*/
    }//GEN-LAST:event_CreatePet_BredFieldMousePressed

    private void CreatePet_SpeciesFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_SpeciesFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_SpeciesFielActionPerformed

    private void CreatePet_SpeciesFielMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_SpeciesFielMousePressed
        /*if (CreatePet_SpeciesFiel.getText().equals("Ingrese su Apellido")){
            CreatePet_SpeciesFiel.setText("");
            CreatePet_SpeciesFiel.setForeground(Color.black);
        }
        if (CreatePet_NameField.getText().equals("Ingrese Nombre")){
            CreatePet_NameField.setText("");
            CreatePet_NameField.setForeground(Color.black);
        }
        if (CreatePet_BredField.getText().isEmpty()){
            CreatePet_BredField.setText("Ingrese Raza");
            CreatePet_BredField.setForeground(Color.gray);
        }
        if (CreatePet_ColorField.getText().isEmpty()){
            CreatePet_ColorField.setText("Ingrese Color");
            CreatePet_ColorField.setForeground(Color.gray);
        }
        if (CreatePet_SexField.getText().isEmpty()){
            CreatePet_SexField.setText("Ingrese Sexo");
            CreatePet_SexField.setForeground(Color.gray);
        }
        if (CreatePet_DateOfBirthField.getText().isEmpty()){
            CreatePet_DateOfBirthField.setText("YYYY-MM-DD");
            CreatePet_DateOfBirthField.setForeground(Color.gray);
        }
        */
    }//GEN-LAST:event_CreatePet_SpeciesFielMousePressed

    private void CreatePet_NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePet_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePet_NameFieldActionPerformed

    private void CreatePet_NameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePet_NameFieldMousePressed
        /*if (CreatePet_NameField.getText().equals("Ingrese Nombre")){
            CreatePet_NameField.setText("");
            CreatePet_NameField.setForeground(Color.black);
        }
        if (CreatePet_SpeciesFiel.getText().isEmpty()){
            CreatePet_SpeciesFiel.setText("Ingrese Especie");
            CreatePet_SpeciesFiel.setForeground(Color.gray);
        }
        if (CreatePet_BredField.getText().isEmpty()){
            CreatePet_BredField.setText("Ingrese Raza");
            CreatePet_BredField.setForeground(Color.gray);
        }
        if (CreatePet_ColorField.getText().isEmpty()){
            CreatePet_ColorField.setText("Ingrese Color");
            CreatePet_ColorField.setForeground(Color.gray);
        }
        if (CreatePet_SexField.getText().isEmpty()){
            CreatePet_SexField.setText("Ingrese Sexo");
            CreatePet_SexField.setForeground(Color.gray);
        }
        if (CreatePet_DateOfBirthField.getText().isEmpty()){
            CreatePet_DateOfBirthField.setText("YYYY-MM-DD");
            CreatePet_DateOfBirthField.setForeground(Color.gray);
        }
      */
    }//GEN-LAST:event_CreatePet_NameFieldMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreatePet().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePet;
    private javax.swing.JTextField CreatePet_BredField;
    private javax.swing.JButton CreatePet_BtnCreate;
    private javax.swing.JButton CreatePet_BtnExit;
    private javax.swing.JTextField CreatePet_ColorField;
    private javax.swing.JTextField CreatePet_DateOfBirthField;
    private javax.swing.JTextField CreatePet_DocumentOwner;
    private javax.swing.JTextField CreatePet_NameField;
    private javax.swing.JTextField CreatePet_SexField;
    private javax.swing.JTextField CreatePet_SpeciesFiel;
    private javax.swing.JLabel CreatePet_lblBred;
    private javax.swing.JLabel CreatePet_lblColor;
    private javax.swing.JLabel CreatePet_lblDate;
    private javax.swing.JLabel CreatePet_lblDocumentOwner;
    private javax.swing.JLabel CreatePet_lblNamepet;
    private javax.swing.JLabel CreatePet_lblSex;
    private javax.swing.JLabel CreatePet_lblSpecies;
    private javax.swing.JLabel CreateUser_lblSubTittle;
    // End of variables declaration//GEN-END:variables
}
